- public_html/profiles/social/modules/social_features/social_user/config/install/views.view.user_admin_people.yml
Add a admin/people view with bulk operations copied from the standard install profile.
See DS-99 and manual tests DS-211 and DS-230.
> DS-99 - Add a admin/people view with bulk operations

- public_html/profiles/social/modules/development/social_devel/social_devel.info.yml
- public_html/profiles/social/modules/social_features/social_user/config/install/core.entity_form_display.user.user.default.yml
- public_html/profiles/social/modules/social_features/social_user/config/install/core.entity_form_display.user.user.register.yml
- public_html/profiles/social/modules/social_features/social_user/social_user.links.menu.yml
- public_html/profiles/social/modules/social_features/social_user/src/Plugin/Menu/SignupMenuLink.php
- Added two entity form displays for the user entity.
- Added "sign up" link to user.register in account menu.
- Disable the signup link for authenticated users.
> DS-116 - As AN I want to sign-up to the platform

- public_html/profiles/social/modules/social_features/social_user/social_user.install
Only task needed:
- Set-up permissions on installation of social_user module so LU can edit own username by default
> DS-130 - As LU I want to Edit my account details

- behat/features/capabilities/login/blocked_user.feature
- public_html/profiles/social/modules/social_features/social_user/src/Form/SocialUserLoginForm.php
----
*Feature:* Notification that account is blocked
*Benefit:* In order to know what the problem is
*Role:* As User
*Goal/desire:* I want to get a message when I try to login but my account is blocked
----
> As User I want to get a message when I try to login but my account is blocked

- public_html/profiles/social/modules/social_features/social_user/config/install/user.flood.yml
HTT:
- Reinstall site
- In new SocialUserLoginForm set some breakpoints to examine the flood settings
- Execute test DS-239
**Unit test is still in the making. Can't get it to work :(**
> Set user flood settings

- public_html/profiles/social/modules/social_features/social_core/social_core.info.yml
> DS-315 by jaapjan: add contact module as dependency

- behat/features/capabilities/comment/comment-create.feature
- behat/features/capabilities/comment/comment-view.feature
- public_html/profiles/social/modules/social_features/social_comment/config/install/core.entity_view_display.comment.comment.default.yml
- public_html/themes/socialbase/socialbase.theme
- public_html/themes/socialbase/templates/comment/comment.html.twig
1. Reinstall the site
2. Run MT at https://goalgorilla.cloudshards.net/browse/DS-472
> DS-187 As User I want to see Comments when I have the visibility permissions

- public_html/profiles/social/modules/social_features/social_core/social_core.info.yml
- do a reinstall
- login as Admin and see you can change / add URL Alias
- login as LU see that you can't change / add URL Alias
> DS-149 As ADMIN I want to change the URL path of a node

- behat/features/capabilities/comment/comment-view-thread.feature
- behat/features/capabilities/comment/comment-view.feature
- public_html/profiles/social/modules/social_features/social_comment/social_comment.module
- public_html/themes/socialbase/socialbase.theme
1. Reinstall the site
2. Run MT at https://goalgorilla.cloudshards.net/browse/DS-477
> DS-188 As User I want to see the Comments thread when I have the visibility permissions

- behat/features/capabilities/comment/comment-delete.feature
- public_html/profiles/social/modules/social_features/social_comment/social_comment.install
- public_html/profiles/social/modules/social_features/social_comment/social_comment.module
- public_html/profiles/social/modules/social_features/social_comment/social_comment.permissions.yml
1. Reinstall the site
2. Run MT at https://goalgorilla.cloudshards.net/browse/DS-478
> DS-191 - As LU I want to delete Comments I am the author of

- behat/features/capabilities/comment/comment-edit.feature
- public_html/profiles/social/modules/social_features/social_comment/social_comment.services.yml
- public_html/profiles/social/modules/social_features/social_comment/src/SocialCommentBreadcrumbBuilder.php
- Added behat comment-edit.feature
- Added SocialCommentBreadcrumbBuilder service 
(see: https://www.palantir.net/blog/d8ftw-breadcrumbs-work)
1. Reinstall the site
2. Run MT at https://goalgorilla.cloudshards.net/browse/DS-482
> DS-321 - AS LU I want to edit a comment if I am the author

- public_html/profiles/social/modules/social_features/social_core/config/install/node.settings.yml
- public_html/profiles/social/modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- Added node.settings.yml
- Uses admin theme on node add / edit pages
- Added proper SocialPageTitleBLock info
- getRevisionAuthor doesn't update the user when we update author information
- Time() ofcourse isn't correct
Test please by doing manual test again :)
> DS - 182 - As ADMIN I want to change the authoring information of a node

- public_html/profiles/social/modules/contrib/r4032login/config/install/r4032login.settings.yml
- public_html/profiles/social/modules/social_features/social_core/social_core.routing.yml
- public_html/profiles/social/modules/social_features/social_core/src/Controller/SocialCoreController.php
> DS-217 by jochemvn, Create custom 403 page with custom message

- behat/features/capabilities/event/event-create.feature
- behat/features/capabilities/event/event-overview.feature
- behat/features/capabilities/search/search-content.feature
- behat/features/capabilities/topic/topic-overview.feature
- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_content.yml
- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_users.yml
- Uncomment address fields for event behat tests 
- Fix cache settings for Search Views. 
- Fix `Then I should see the heading` steps
> DS-669 Maintenance Sprint 5 (Behat Tests)

- public_html/profiles/social/modules/social_features/social_comment/social_comment.module
- public_html/profiles/social/modules/social_features/social_post/config/install/core.entity_view_display.post.post.default.yml
- public_html/profiles/social/modules/social_features/social_post/config/install/core.entity_view_display.post.post.teaser.yml
- public_html/profiles/social/modules/social_features/social_post/post.page.inc
- public_html/profiles/social/modules/social_features/social_post/social_post.module
- public_html/profiles/social/modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostFormatter.php
- public_html/themes/socialbase/templates/post/comment--field-post-comments.html.twig
- public_html/themes/socialbase/templates/post/field--field-post-comments.html.twig
- Sorting of comments and ordering
- Show all comments-button
- Markup post.html.twig
> Some small fixes regarding Post functionality

- behat/features/capabilities/profile/view-profile-hero.feature
- public_html/themes/socialbase/templates/profile/profile--profile--hero.html.twig
1. Added the fields to the template (are already in the hero view mode)
2. Updated the behat test
3. Update MT (https://goalgorilla.cloudshards.net/browse/DS-739)
4. Updated regression front end fixes to make sure the fields will be rendered correctly whenever they are in HiFi (just tried to stick to normal template)
> DS-795 - add function and organisation in profile hero area

- dev-scripts/content/entity/user.yml
- public_html/profiles/social/modules/development/social_demo/src/Content/SocialDemoUser.php
> DS-735 demo content profiles

- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_content.yml
- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_users.yml
- public_html/profiles/social/modules/social_features/social_search/social_search.links.task.yml
- public_html/profiles/social/modules/social_features/social_search/social_search.services.yml
- public_html/profiles/social/modules/social_features/social_search/src/SocialSearchBreadcrumbBuilder.php
- Added search terms to the link that says "If you are searching for content/users, click here"
- Added search local tasks
- Added breadcrumbs for search pages
> DS-724 - Add search terms to the link that says "If you are searching for content/users, click here"

- public_html/profiles/social/modules/social_features/social_profile/social_profile.module
- public_html/themes/socialbase/templates/profile/profile--profile--teaser.html.twig
- Fixed button links in profile teaser
> DS-797 - Link view profile button in a user teaser to stream page other than information

- public_html/profiles/social/modules/social_features/social_core/config/install/block.block.anhomepageheroblock.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/block_content.type.hero_call_to_action_block.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/core.entity_form_display.block_content.hero_call_to_action_block.default.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/core.entity_view_display.block_content.hero_call_to_action_block.default.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_call_to_action_link.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_hero_image.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_text_block.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.storage.block_content.field_call_to_action_link.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.storage.block_content.field_hero_image.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/field.storage.block_content.field_text_block.yml
- public_html/profiles/social/modules/social_features/social_core/config/install/image.style.hero_background.yml
- public_html/profiles/social/modules/social_features/social_core/social_core.info.yml
- public_html/profiles/social/modules/social_features/social_core/social_core.install
- public_html/profiles/social/modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_image.yml
- public_html/themes/socialbase/templates/block/block--anhomepageheroblock.html.twig
> DS-858 AN homepage hero area

- behat/features/capabilities/group/group-edit-open.feature
- public_html/profiles/social/modules/social_features/social_group/social_group.module
> DS-646 - Group manager edit my group

- public_html/profiles/social/modules/social_features/social_group/social_group.module
> DS-767 by jochemvn: As a Group Manager I want to add a user to the group

- public_html/themes/socialbase/css/materialize.css
- public_html/themes/socialbase/css/src/materialize.scss
- public_html/themes/socialbase/css/src/materialize/_preview.scss
- public_html/themes/socialbase/socialbase.theme
- public_html/themes/socialbase/templates/html--node--preview.html.twig
- public_html/themes/socialbase/templates/node/node--default.html.twig
- public_html/themes/socialbase/templates/page--node--preview.html.twig
- Add new template for preview node
- Add css styles for preview node
> DS-475 by bogdan-hepting: Node preview

- public_html/profiles/social/modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
- public_html/profiles/social/modules/social_features/social_topic/config/install/core.entity_form_display.node.topic.default.yml
- public_html/profiles/social/themes/socialbase/templates/form/fieldset--radios.html.twig
> DS-1193 by bogdan-hepting: Visibility settings in a card

- public_html/profiles/social/modules/custom/dropdown/dropdown.module
- public_html/profiles/social/modules/custom/dropdown/src/Element/Dropdown.php
- public_html/profiles/social/modules/social_features/social_core/config/install/block.block.socialbase_local_tasks.yml
- public_html/profiles/social/modules/social_features/social_post/js/visibility-settings.js
- public_html/profiles/social/modules/social_features/social_post/src/Form/PostForm.php
- public_html/profiles/social/modules/social_features/social_user/templates/account-header-links.html.twig
- public_html/profiles/social/themes/socialbase/socialbase.theme
- public_html/profiles/social/themes/socialbase/templates/dropdown.html.twig
- public_html/profiles/social/themes/socialbase/templates/form/form--post-edit.html.twig
- public_html/profiles/social/themes/socialbase/templates/form/form-element--field-visibility.html.twig
- public_html/profiles/social/themes/socialbase/templates/form/form-element-label--dropdown.html.twig
- public_html/profiles/social/themes/socialbase/templates/form/input--radio--dropdown.html.twig
- public_html/profiles/social/themes/socialbase/templates/navigation/menu--account--socialbase-account-menu.html.twig
- public_html/profiles/social/themes/socialbase/templates/post/post--teaser.html.twig
- public_html/profiles/social/themes/socialbase/templates/post/post.html.twig
The below stories & subtasks are fixed in this branch: 
Stories:
Subtasks
DEV: 
FRONT:
Please make sure to test:
- Create & Edit post
- Make sure to test the Dropdown visibility. 
- See if public posts are really public.
- See that you can NOT change visibility
- See that correct visibility settings are shown on front for LU / stream on profile for LU (another users profile) / Group stream
> Theming / Dev - Edit & Create & Delete Post 

- dev-scripts/install/install_script.sh
- public_html/profiles/social/modules/custom/activity_logger/config/install/message.type.create_event_group.yml
- public_html/profiles/social/modules/custom/activity_logger/config/install/message.type.create_post_group.yml
- public_html/profiles/social/modules/custom/activity_logger/config/install/message.type.create_topic_group.yml
- public_html/profiles/social/modules/development/social_demo/src/Content/SocialDemoGroup.php
> Some more polishing

- dev-scripts/install/install_script.sh
- public_html/profiles/social/modules/development/social_demo/content/entity/comment.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/event.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/file.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/group.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/post.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/topic.yml
- public_html/profiles/social/modules/development/social_demo/content/entity/user.yml
- public_html/profiles/social/modules/development/social_demo/src/Content/SocialDemoComment.php
- public_html/profiles/social/modules/development/social_demo/src/Content/SocialDemoEvent.php
**Do a reinstall of the site and notice the following:**
> DS-927 - Democontent

- public_html/profiles/social/modules/social_features/social_core/src/Plugin/Field/FieldFormatter/CommentNodeFormatter.php
- public_html/profiles/social/tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
> DS-1394 by ribel: As a LU I do not want to see replies to comments in the activity stream

- .travis.yml
- docker-compose-travis.yml
- docker-compose.yml
- public_html/profiles/social/tests/behat/features/bootstrap/SocialMinkContext.php
- public_html/profiles/social/tests/behat/features/capabilities/account/blocked_user.feature
- travis_artifacts/.gitignore
- travis_artifacts/readme.txt
See https://docs.travis-ci.com/user/uploading-artifacts/
HTT:
Check that you can login in AWS console with the GG account:
https://console.aws.amazon.com/s3/
You should see two buckets (one bucket for each project) for OS and WIM.
Open the OS bucket and go the deepest you can. You should see a screenshot there.
Check the logs from 
https://travis-ci.org/goalgorilla/drupal_social/builds/143872806
The first Behat test creates the screenshots which are uploaded at the end of the logs
> Travis artifacts screenshots

- public_html/profiles/social/themes/socialbase/components/asset-builds/css/materialize.css
- public_html/profiles/social/themes/socialbase/components/materialize/_cards.scss
> DS-1131 by bogdan-hepting: Fix bug on mobile view

- public_html/profiles/social/modules/social_features/social_user/social_user.links.menu.yml
- public_html/profiles/social/modules/social_features/social_user/social_user.links.task.yml
- public_html/profiles/social/tests/behat/features/capabilities/account/blocked_user.feature
- public_html/profiles/social/tests/behat/features/capabilities/account/login.feature
> DS-1440 login button gone

- dev-scripts/install/install_script.sh
- public_html/profiles/social/modules/social_features/social_event/config/install/block.block.views_block__upcoming_events_upcoming_events_group.yml
- public_html/profiles/social/modules/social_features/social_event/config/install/views.view.upcoming_events.yml
- public_html/profiles/social/modules/social_features/social_group/config/install/block.block.views_block__group_members_block_newest_members.yml
- public_html/profiles/social/modules/social_features/social_group/config/install/views.view.group_members.yml
- public_html/profiles/social/modules/social_features/social_topic/config/install/block.block.views_block__latest_topics_group_topics_block.yml
- public_html/profiles/social/modules/social_features/social_topic/config/install/views.view.latest_topics.yml
- public_html/profiles/social/themes/socialbase/socialbase.theme
> DS-1543 missing blocks on group home

- public_html/profiles/social/modules/contrib/profile/src/ProfileAccessControlHandler.php
- public_html/profiles/social/modules/social_features/social_core/config/install/user.role.authenticated.yml
- public_html/profiles/social/modules/social_features/social_profile/social_profile.install
> DS-1542 - LU should not be able to delete own profile

- public_html/profiles/social/modules/social_features/social_comment/social_comment.module
- public_html/profiles/social/modules/social_features/social_post/js/keycode-submit.js
- public_html/profiles/social/modules/social_features/social_post/social_post.libraries.yml
- public_html/profiles/social/modules/social_features/social_post/src/Form/PostForm.php
> DS-1560 Enable CTRL+Enter to submit a post

- public_html/profiles/social/modules/social_features/social_search/config/install/block.block.searchgroupsblock.yml
- public_html/profiles/social/modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_content.yml
- public_html/profiles/social/modules/social_features/social_search/config/install/views.view.search_groups.yml
- public_html/profiles/social/modules/social_features/social_search/social_search.links.task.yml
- public_html/profiles/social/modules/social_features/social_search/src/Form/SearchGroupsForm.php
- public_html/profiles/social/modules/social_features/social_search/src/Plugin/Block/SearchGroupsBlock.php
- public_html/profiles/social/modules/social_features/social_user/config/install/user.mail.yml
- public_html/profiles/social/tests/behat/features/bootstrap/FeatureContext.php
- public_html/profiles/social/tests/behat/features/capabilities/group/group-edit-open.feature
- public_html/profiles/social/tests/behat/features/capabilities/search/search-groups.feature
- public_html/profiles/social/themes/socialbase/socialbase.theme
> DS-1523 - Search groups

- public_html/profiles/social/themes/socialbase/components/asset-builds/css/type.css
- public_html/profiles/social/themes/socialbase/components/components/type/type.scss
- public_html/profiles/social/themes/socialbase/socialbase.info.yml
Clear cache and it should work.
- check all editor style as expected from the theme.
> DS-1546 by maikel-koopman: stylesheet for ckeditor

- public_html/profiles/social/modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_hero_image.yml
- public_html/profiles/social/modules/social_features/social_event/config/install/field.field.node.event.field_event_image.yml
- public_html/profiles/social/modules/social_features/social_group/config/install/field.field.group.open_group.field_group_image.yml
- public_html/profiles/social/modules/social_features/social_profile/config/install/field.field.profile.profile.field_profile_image.yml
- public_html/profiles/social/modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_image.yml
> DS-1612: Make image style hero smaller

- public_html/profiles/social/modules/social_features/social_editor/config/install/filter.format.basic_html.yml
> DS-1091: As a LU when posting post/comments carriage returns should be respected

- public_html/profiles/social/modules/custom/entity_access_by_field/entity_access_by_field.module
> DS-1674: Unpublished events are not displayed on user overview

- public_html/profiles/social/modules/social_features/social_user/js/user-form-protection.js
- public_html/profiles/social/modules/social_features/social_user/social_user.libraries.yml
- public_html/profiles/social/modules/social_features/social_user/social_user.module
> DS-1559: Add JS dialog forcing to change password after first time login

- dev-scripts/trigger_dockerhub.sh
Script for Travis to be able to trigger an automated build in the Docker Hub. Merge this before the Open Social PR.
HTT: Check code and see that it worked in
https://travis-ci.org/goalgorilla/open_social/builds/154396720
This triggered the build in the Docker Hub Drupal Social repo
> DS-1847 trigger automated build on Docker Hub with the new composer workflow.

- dev-scripts/cron/cron.sh
- docker_build/cron/Dockerfile
- docker_build/cron/cron.sh
> DS-2034 by jochemvn: Change the way the cron is being run

- Dockerfile
- composer.json
- docker_build/drupal8/composer.json
Instead of using a separate composer.json file for the docker image. It should fix issue #291 as well.
> DS-2065 by jaapjan: add drush as a dependency in the main composer json

- dev-scripts/install/install_script.sh
> On install, flush image caches after creating new demo content

- composer.json
This PR is to prepare the repo for the upcoming 8.4.0 release of Drupal. Phpunit needs an update. Also I've added the drupal console (dev only)
> Update some deps for drupal 8.4.0

- docker-compose.blackfire.yml
- docker-compose.yml
Referring to #336 
The idea is from https://docs.docker.com/compose/extends
> Revert BlackFire for contributors and separate docker-compose for staff

- composer.json
- docker-compose-ci.yml
- docker-compose.blackfire.yml
- docker-compose.yml
Adding redis module.
See also: https://github.com/goalgorilla/open_social_docker/pull/14 (has to be merged as well)
> Performance Fixes: Add redis

- .travis.yml
- composer.json
- docker-compose-ci.yml
We were facing build failure on PRs here https://github.com/goalgorilla/open_social/pulls due to https://github.com/squizlabs/PHP_CodeSniffer/issues/2821#issuecomment-728779752.
Update docker-composer-ci.yml file to have the latest changes.
Add release version of `squizlabs/php_codesniffe` and `dealerdirect/phpcodesniffer-composer-installer` to composer.json
Make sure that docker-composer-ci and docker-compose yml files have the same configurations.
> Drupal coder and ci docker composer file change.

- composer.json
Update the Drush to version 10.
See: 
1. https://github.com/goalgorilla/open_social/pull/2487
> Issue #3229480 by navneet0693: Changed the version of drush to 10.

- composer.json
This PR is dependent of https://github.com/goalgorilla/open_social/pull/2919
> Update drupal/core-dev version to 9.3.x

- composer.json
Update scripts path and make them absolute
> Change paths on scripts to absolute

- composer.json
Add one extra composer command, it's a quality of life improvement
> Add extra composer script commands

- composer.json
- rector.php
1. Update Rector versions.
2. Update Rector.php file.
>  Update dependencies.
