public_html/profiles/social/modules/social_features/social_user/social_user.install
public_html/profiles/social/modules/social_features/social_user/social_user.module

**HTT**
- Perform a new installation of the site, since some permissions were added
- Create a new account (user_role => authenticated user)
- Login as the new user
- Edit your own account
- Notice the 'cancel account' button next to the save button
- Click it!
- Notice there are only 3 options to choose from. It's no longer possible to choose 'Delete the account and its content.'
- Choose one of the options (it will fail since no mail was send :-1: )
- Login as an administrator. Notice the option is still there.
- Execute manual test [DS-391](https://goalgorilla.cloudshards.net/browse/DS-391) in [DS-387](https://goalgorilla.cloudshards.net/browse/DS-387)
As an admin I can also access this form from the people overview (bulk operation). No changes were made here, since the 'administer …

DS-132 - As LU I want to cancel my account

---

public_html/profiles/social/modules/social_features/social_core/social_core.module
public_html/profiles/social/modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
public_html/profiles/social/modules/social_features/social_core/templates/page-hero-data.html.twig

- Added group link to page title hero block when an event or topic belongs to the group.

DS-639 - As a LU I want to see which group the content belongs to

---

public_html/profiles/social/modules/social_features/social_group/social_group.module

DS-705 by jochemvn: Remove local tab delete from group homepage

---

public_html/profiles/social/modules/social_features/social_group/config/install/block.block.views_block__group_members_block_newest_members.yml
public_html/profiles/social/modules/social_features/social_group/config/install/core.entity_view_display.group_content.open_group-group_membership.default.yml
public_html/profiles/social/modules/social_features/social_group/config/install/views.view.group_members.yml
public_html/profiles/social/modules/social_features/social_group/social_group.links.task.yml
public_html/profiles/social/modules/social_features/social_group/social_group.module
public_html/profiles/social/modules/social_features/social_group/social_group.services.yml
public_html/profiles/social/modules/social_features/social_group/src/Controller/SocialGroupController.php
public_html/profiles/social/modules/social_features/social_group/src/Routing/RouteSubscriber.php
public_html/themes/socialbase/socialbase.theme
public_html/themes/socialbase/templates/block/block--views-block--group_members-block-newest-members.html.twig

- Added "Group Members" views. Alter output of this view with profile teasers
- Replaced default Group "Members" page with views "Group Members" page
- Added "Newest Members" block to the Group page

DS-648 - As a LU I want to see the members of a group

---

public_html/profiles/social/modules/social_features/social_event/social_event.group.permissions.yml
public_html/profiles/social/modules/social_features/social_event/src/Controller/SocialEventController.php
public_html/profiles/social/modules/social_features/social_event/src/Plugin/Block/EnrollActionBlock.php
public_html/profiles/social/modules/social_features/social_group/config/install/group.role.open_group-group_manager.yml
public_html/profiles/social/modules/social_features/social_group/config/install/group.role.open_group-member.yml
public_html/profiles/social/modules/social_features/social_group/src/Routing/RouteSubscriber.php

If an event is posted inside a group we have to use custom permission checks to make sure the user is allowed to enrol to the event.

DS-722 by jaapjan: outsiders are not allowed to enrol to an event in group

---

public_html/profiles/social/modules/social_features/social_group/config/install/group.role.open_group-group_manager.yml

Revoked 'administrer group' permission for group mangers. This overrides all other permissions.
**HTT:**

DS-707 - GM Should edit content of others in a group

---

public_html/profiles/social/modules/social_features/social_comment/social_comment.module
public_html/profiles/social/modules/social_features/social_comment/src/Routing/RouteSubscriber.php
public_html/profiles/social/modules/social_features/social_comment/src/SocialCommentBreadcrumbBuilder.php
public_html/profiles/social/tests/behat/features/capabilities/comment/comment-edit.feature
public_html/profiles/social/tests/behat/features/capabilities/comment/comment-view-thread.feature
public_html/profiles/social/tests/behat/features/capabilities/post/post-comments.feature
public_html/profiles/social/themes/socialbase/css/materialize.css
public_html/profiles/social/themes/socialbase/css/src/materialize/_forms.scss
public_html/profiles/social/themes/socialbase/jade/reply-edit.jade
public_html/profiles/social/themes/socialbase/socialbase.theme
public_html/profiles/social/themes/socialbase/templates/comment/comment.html.twig
public_html/profiles/social/themes/socialbase/templates/form/form--comment-form-edit.html.twig
public_html/profiles/social/themes/socialbase/templates/page--comment--edit.html.twig

- The button text changed to "Reply"
- The placeholder text chnaged be "Add a reply"
- The "reply" link is not present
- Add new template for reply edit comment
- Remove the BR between name and timestamp (also in Hi-Fi)

DS-1188: Theme create comment reply functionality

---

public_html/profiles/social/modules/custom/activity_creator/activity.page.inc
public_html/profiles/social/modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
public_html/profiles/social/modules/development/social_demo/src/Content/SocialDemoComment.php
public_html/profiles/social/modules/social_features/social_comment/social_comment.module
public_html/profiles/social/modules/social_features/social_post/post.page.inc
public_html/profiles/social/themes/socialbase/socialbase.theme

h2. Solution
It was not clear what exactly went wrong but these following changes will likely fix it:
- Made sure the activity has the same created date as the entity it was created for.
- Enabled correct caching max age for the timestamps (currently they are not updated and always cached)
- Made sure demo content comments are always in the future.
- Changed the granularity to 1 instead of 2 (e.g. 2 minutes and 1 second ago) for performance and usability reasons **Discussed this with Taco that it was ok**
For background information for the solution see:
https://www.drupal.org/node/2500525

DS-1512 Time ago improvements (comments, post and activity stream)

---

public_html/profiles/social/modules/social_features/social_group/social_group.module

DS-1673: As a Group manager (or admin) I want to see the correct member link on the group page

---

composer.json

Noticed this error in our builds in Travis.
> Deprecation Notice: The callback cweagans\Composer\Patches::postInstall declared at /home/travis/build/goalgorilla/open_social/install/vendor/cweagans/composer-patches/src/Patches.php accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///home/travis/.phpenv/versions/5.6.24/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317
The latest release https://github.com/cweagans/composer-patches/releases should fix this. So I changed the version constraint in the composer.json to make sure to use the latest release instead.

Update cweagons/composerpatches to latest version.

---

.travis.yml

This is a follow-up of https://github.com/goalgorilla/drupal_social/pull/318 and https://github.com/goalgorilla/open_social_scripts/pull/6.
The coding standards check is now ran on Travis CI before any other scripts. It does not *yet* exit with 1 if errors or warnings are found, but this can easily be enabled.

DS-3893 by bramtenhove: Enable coding standards check on Travis

---

composer.json

In order to be able to require front-end libraries via composer, we will need to update the root composer.json file. This PR is basically preparation for the main changes done in the open_social repo.
This change is based on what Acquia Lightning did:
- https://lightning.acquia.com/blog/round-your-front-end-javascript-libraries-composer
- https://github.com/acquia/lightning/releases/tag/2.1.7
**Updates done:**
- Adding asset-packagist repo
- Add installer types
- Set a path for the front-end libraries
Make sure your composer is up to date! We require at least version **1.5.0**, you can update by running `composer self-update`.

DS-4122 - Move front-end libraries to composer.json

---

composer.json

Do not check accessibility when building environment via Travis.
Add depend on package for checking accessibility via a shell script.
- https://jira.goalgorilla.com/browse/DS-4945

DS-4945 Add tracker to Travis

---

docker-compose.yml

This commit adds the blackfire docker image as a container in the
docker-compose file and links it to the web container. This makes
it possible to use the Chrome Blackfire plugin to analyse any
Open Social website.
For this commit to work properly it is required that the Blackfire
probe is added to the open_social_docker:dev image.
For more info on how to use Blackfire in Docker and to find out
what keys you should add to your .bash_profile go to
https://blackfire.io/docs/integrations/docker
This PR requires https://github.com/goalgorilla/open_social_docker/pull/10 to work

Add support for Blackfire profiling to the Open Social docker containers

---

composer.json

Only change needed was this composer.json. 
The changes we talked about in the Docker file are already done a while back:
https://github.com/goalgorilla/open_social_docker/blob/master/Dockerfile
The drush executable is not installed anymore in the container, but a symlink to /var/www/vendor/bin/drush, which is good

Update drush to stable version 9

---

composer.json

Reverts goalgorilla/drupal_social#340
The Drush 9 update has some consequences for drush commands that were overlooked. Since this change may have implications for production websites we're reverting until we can investigate.

Revert "Update drush to stable version 9"

---

composer.json

I am getting an error: 
```
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. Make sure you fix this as Composer 2.0 will error.
```

No uppercase characters on composer.json

---

composer.json

A very easy way to check for dependencies with known vulnerabilities is to use https://github.com/Roave/SecurityAdvisories. This is actually suggested by my PHPStorm instance.
Example:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
- roave/security-advisories dev-master conflicts with zendframework/zendframework[2.3.1].
- Installation request for zendframework/zendframework 2.3.1 -> satisfiable by zendframework/zendframework[2.3.1].
```

Add the security-advisories package to fail on composer updates that try to install insecure packages

---

composer.json
patches/like-dislike-fix-webprofiler.patch

Two small things:
- Update to 8.x-8.x
- Add blackfire/php-sdk
More importantly added [static code analyser](https://github.com/mglaman/drupal-check). It can be used as follows after installation:
`/var/www/vendor/bin/drupal-check /var/www/html/profiles/contrib/social`
It will give you a result like this:
```
root@0f4d2f415f7d:/var/www/html# ../vendor/bin/drupal-check profiles/contrib/social/
764/764 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ------------------------------------------------------------------- 
Line   modules/custom/activity_creator/activity_creator.module            
------ ------------------------------------------------------------------- 
306    Call to deprecated function entity_delete_multiple():              
as of Drupal 8.0.x, will be removed before Drupal 9.0.0. …
```

Add mglaman/drupal-check and blackfire/php-sdk and update to 8.x.

---

docker-compose-ci.yml
docker-compose.blackfire.yml
docker-compose.yml

By adding `:delegated` to the Docker volumes the performance increases drastically.
> The `delegated` configuration provides the weakest set of guarantees. For directories mounted with `delegated` the container’s view of the file system is authoritative, and writes performed by containers may not be immediately reflected on the host file system.

Improve Docker performance by adding :delegated to volumes

---

composer.json

**Problem**
Patches in core are not correctly applied.
**Solution**
Add patchLevel -p2 to drupal/core in composer.json.

Add patchLevel -p2 for drupal/core.

---

composer.json

This PR should not be merged until all open PRs in the goalgorilla/open_social repo are switch over.
**After merging, do not delete this branch until all the `.travis.yml` of the Open Social repo has been updated back to `master`!**

Move to `drupal/social`

---

composer.json

- Updated drupal/core-dev to `~9.2.0`
- Temporarily require `"goalgorilla/open_social": "dev-update/drupal-core-9.2.x "`

Drupal 9.2.x update

---

docker-compose-ci.yml
docker-compose.yml

1. Updated our docker-compose files to the latest compose specification version from v2. See:
https://docs.docker.com/compose/compose-file/compose-versioning/
https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading
2. Removed links and network bridge keys as they are default behavior.
3. Added depends_on key to make sure contains are ready before other containers need them.
4. Read more about them here: https://github.com/compose-spec/compose-spec/blob/master/spec.md
5. This adds 'Docker compose v2' support. Read more here: https://docs.docker.com/compose/cli-command/

Ugraded our docker compose files to compose specifications.

---

.travis.yml
composer.json
docker-compose-ci.yml
docker-compose.blackfire.yml
docker-compose.yml
rector.php

1. Update Drupal core version to 9.3.5 which supports PHP 8.0
2. Updated travis configutation to install PHP 8.0
3. Updated rector.php file to check againt PHP 8.0
4. Changes from https://github.com/goalgorilla/open_social_docker/pull/19 are included for Docker image.
5. Temporarily added: https://github.com/goalgorilla/open_social_scripts/pull/44 branch.

Added PHP 8.0 support.

---

.github/workflows/behat-stability-1.yml
composer.json
docker-compose-ci.yml
docker-compose.yml

With headless chrome we will be improving performance on our tests and moving away from the old firefox webdriver.

Replace selenium and firefox with headless chrome

---

docker-compose.blackfire.yml
docker-compose.yml

Allot of our developers were disabling the cron container for performance reasons, thus why we should remove the  container and when you actually need the cron, you can do it manually. For running the behat tests see: html/profiles/contrib/social/tests/behat/README.md.
We recently added the docker-compose.nginx.yml, which runs in addition to the default docker-compose.yml. To have the docker-compose files consistent with each other, the docker-compose.blackfire.yml should be adjusted to run in addition instead of standalone.

Removed the redundant cron docker container

---

docker-compose.yml

There is an error on the Linux machine after executing `docker-compose up -d`
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.solr.environment.PARTIAL_SEARCH_ENABLED contains false, which is an invalid type, it should be a string, number, or a null
```

Fix error on Linux machine

---

composer.json
readme.md

Adding extra commands to our composer.json file:
- docker-up: starts up docker proxy and docker instances.
- docker-stop: stop docker.
- docker-shell: ssh into web docker container.
- os-install: install open social without optional modules.
- phpstan (inside web container): executes phpstan checks.
- phpstan-baseline (inside web container): regenerate phpstan baseline file.
- phpcs (inside web container): executes phpcs checks.
- phpunit (inside web container): executes phpunit checks.

Add extra composer commands

---

.github/workflows/behat-stability-1.yml
composer.json
ecs.php
rector.php

Placeholder experimentation PR for https://github.com/goalgorilla/open_social/pull/3148
1. Remove upgrade_status requirement.
2. Set PHP 7.4 as basic.
This PR is rebased to minimum changes after we got green on the above mentioned PR.

Set PHP 7.4 as base in Rector and ECS and remove upgrade_status module

---

docker-compose-ci.yml
docker-compose.yml

Since we are not supporting PHP 8.1, let's update our docker images to use PHP 8.1
https://getopensocial.atlassian.net/browse/PROD-25687
This is a PR from a series of 4 PRs that should be merged in the following order: 
1. https://github.com/goalgorilla/open_social_dev/pull/70
2. https://github.com/goalgorilla/open_social/pull/3460
3. https://github.com/goalgorilla/open_social/pull/3457
4. https://github.com/goalgorilla/drupal_social/pull/392 ( this PR )
They are ALL BC and should not cause any breaking change for our local development

Update our Doocker setup to use PHP 8.1 images

---

composer.json

It was returning an error ("permission denied" or "file not found") when trying to execute the command without /bin/bash.

Internal | Fix broken `install-open-social` Composer command

---

composer.json

In preparation of Drupal 11 readiness, we move rector form open_social into open_social_dev.
Issue reference:
https://getopensocial.atlassian.net/browse/PROD-31149

PROD-31149: Remove rector form profil and add it into open_social_dev.
